//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Магазин
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int Номер_заказа { get; set; }
        public string Состав_заказа { get; set; }
        public System.DateTime Дата_заказа { get; set; }
        public System.DateTime Дата_доставки { get; set; }
        public int Пункт_выдачи { get; set; }
        public string ФИО_клиента { get; set; }
        public int Код_для_получения { get; set; }
        public string Статус_заказа { get; set; }
    
        public virtual Пункт_выдачи Пункт_выдачи1 { get; set; }
    }
}
