//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Магазин
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Единица_измерения { get; set; }
        public int Стоимость { get; set; }
        public int Размер_максимально_возможной_скидки { get; set; }
        public string Производитель { get; set; }
        public string Поставщик { get; set; }
        public string Категория_товара { get; set; }
        public int Действующая_скидка { get; set; }
        public int Кол_во_на_складе { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
    }
}
